services:
  bridge_backend:
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/app
    scale: 1
    networks:
      - custody_global_network


  bridge_webserver:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - custody_global_network
    ports:
      - 3003:8080
    depends_on:
      - bridge_backend


networks:
  custody_global_network:
    external: true
