name: Deploy to dev server
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Deploy to dev server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_2 }}
        HOST: 49.13.230.22
        USER: root
        container_name: custody-keys-bridge-dev
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
         ssh -i private_key   -o StrictHostKeyChecking=no  $USER@$HOST  "
           cd /root/dev/custody-keys-bridge
           git pull --recurse-submodules
           cd rox-custody_common-modules
           git checkout dev
           git pull
           cd ..
           docker build -t $container_name .
           docker stop $container_name  && docker rm $container_name
           docker run -d -p 5001:3003 --name=$container_name  --restart=unless-stopped  $container_name "
